# Generated by Django 4.0.6 on 2022-07-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='classe',
            field=models.CharField(choices=[('Classe AB', 'Classe AB - renda domiciliar per capita acima de R$ 4591'), ('Classe C', 'renda domiciliar entre R$ 1064 e R$ 4591'), ('Classe D', 'renda domiciliar entre R$ 768 e R$ 1064'), ('Classe E', 'renda domiciliar até R$ 768')], max_length=50),
        ),
    ]
